### ISSUE TITLE
logo proposal for SpectralPlayer

### ISSUE THREAD

**Issue by candyskull920** [Scerelyn/SpectralPlayer#1]
Hello @Scerelyn 
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project for free, I can provide a logo for your application

Good day
Skull C.

**Comment by Scerelyn** [comment]
Hello @candyskull920, I would love to take your offer for a logo. I aim to have the UI's color theme be white on black, so a logo matching those colors would be good. As for a logo design, I figured a little ghost wearing headphone would be neat.

**Comment by candyskull920** [comment]
The sooner I'll get my proposals.

Good day
Skull C.

**Comment by candyskull920** [comment]
Hello @Scerelyn 

This is my proposal, I can make any modification you want, either in color or design.
![sin-titulo-1](https://user-images.githubusercontent.com/43797200/46640001-8d5b2280-cb37-11e8-9d9f-b55add7a4ced.jpg)
![fantasma-logo-2](https://user-images.githubusercontent.com/43797200/46640000-8cc28c00-cb37-11e8-8858-4917cb91d3df.jpg)

Good day
Skull C.

**Comment by Scerelyn** [comment]
This proposal works, but I would make the ghost and headphones white, and have that over a black circle for the background.

**Comment by candyskull920** [comment]
Hi @Scerelyn 
Here is my proposal with the modification you requested.
When I want I can do the pull requests to add it to the readme or you can do it yourself if you wish.
![audifnos-3](https://user-images.githubusercontent.com/43797200/46687099-06a25600-cbc8-11e8-979a-cbcc51d16926.png)
![logo-version-5](https://user-images.githubusercontent.com/43797200/46687111-0a35dd00-cbc8-11e8-8f34-540852fb3699.jpg)

I can improve any detail that I consider necessary

Good day 
Skull C.

**Comment by Scerelyn** [comment]
The second one looks really good. If you could reduce it down to two or three colors to keep it simplistic, it would be perfect

**Comment by candyskull920** [comment]
Hi @scerelyn
soon I will be going over the logo with the modifications that it asks for and I can do a pull requests to add it to the readme...

Skull C.

**Comment by candyskull920** [comment]
![fantasma-logo-version-6](https://user-images.githubusercontent.com/43797200/46994287-d6841700-d0e1-11e8-9257-9f30eb0846bc.png)

**Comment by candyskull920** [comment]
Hi @Scerelyn 
sorry these are the ones proposed with the 2 colors, as you requested.
I await your approval to do the pull requests to add the logo to readme.
monochromatic proposal 1
![fantasma-logo-version-6 1](https://user-images.githubusercontent.com/43797200/47039171-4978a680-d151-11e8-8540-1444576a9143.png)
monochromatic proposal 2
![fantasma-logo-version-7-cambio](https://user-images.githubusercontent.com/43797200/47039197-61e8c100-d151-11e8-81fc-317fdb2453a6.png)

Good day
Skull C.

**Comment by Scerelyn** [comment]
Proposal two looks the best for this project. Fork this repo, make the changes, and make a pull request and I will happily approve

**Comment by Scerelyn** [comment]
Merged the logo, thanks for making the logo for the project!
